### PR TITLE
[CartoonsGR] various search fixes

### PR DESCRIPTION
**Pull request by host505**
hopefully now all search modes are on par with the sites'

### CODE REVIEW

**Comment by bugatsinho** [comment]
actually the replace isn't so pythonic mate, try to use urllib.quote_plus()

**Comment by bugatsinho** [comment]
also, I have to check if there was a reason for urllib.quote as the terms-queries have to be saved on a database! are you sure there isn't any issue there?

**Comment by bugatsinho** [comment]
I checked the search function as it is for gamatokids and it works without the need of the replace or the quote_plus(). how did you come with those changes?if you want inbox me mate!

**Comment by host505** [comment]
If your search term is more than 1 words, it only works through search menu/input term.
If you hit that cached search term it doesn't work.
Also doesn't work through Gamato Movies/Search menu.
Same for tenies-online.

**Comment by host505** [comment]
I fixed gamato with urllib.quote_plus() (I now see the mess-up I made - but it was working), but cloudflare got me again on tenies-online...
I'll have to test later

**Comment by host505** [comment]
ok I removed unnecessary transformations, I hope it makes more sense now.
.replace() on line 464 seems inevitable, doesn't work with urllib.quote_plus().
All searches are properly written in search.db.
I hope you understood the problem, maybe you have a better solution, but this seems to be working for me.

**Comment by bugatsinho** [comment]
cloudflare also for me!! thank you for the explanation...i will check again later

**Comment by bugatsinho** [comment]
i was using dif words, search and term, the one is to be saved and the other is to be used for the search function

**Comment by host505** [comment]
That's on Search() right? I didn't touch that.
The problem is that search through saved term did't have '+' instead of space if 2+ words

**Comment by host505** [comment]
Also, forgot to mention, this also fixes searching with Greek words from some menus (gamato movies/search, tenies-online/search)

**Comment by bugatsinho** [comment]
there is an issue mate the files on the git aren't correct just found that the search.py is too old

**Comment by bugatsinho** [comment]
In new search the search query is with quote_plus() as you can see here
and the url is created with that query
image

so the error is on the separated search functions

**Comment by host505** [comment]
Yes, that part is working, and I didn't touch that.
But the term is saved with unquote_plus. You can't do otherwise, hence the replace I made.
If you touch the separate functions (Search_gamato() and teniesonline.search()) something else breaks.
Anyway, you basically have 3 different search cases for each site, and you have to account various search term conditions: 1 word, 2+ words, Greek, English etc. 
It's hard to go into details for each one, but with the changes I made they all work, under all conditions.

**Comment by bugatsinho** [comment]
the misunderstanding  is that if you check your database we will see that URL comes with quote_plus() that is why on else: inline https://github.com/bugatsinho/bugatsinho.github.io/blob/7fae57eabd74455139dd59cb2ac56b5ee15a738b/plugin.video.cartoonsgr/default.py#L463 I added only URL...now I have to find out why the URL from database returns without the quote_plus

**Comment by bugatsinho** [comment]
also inline 410 is when you get the saved items with url so this is weird!

**Pull request merged**
