### PR TITLE
[CartoonsGR] Restore tenies-online & fix for py3/k19 + other changes

### PR DESCRIPTION
**Pull request by host505**
Please see commit titles, keep what you wish (or not lol)
Here's a .zip with all the changes for you (or anyone) to test:
https://github.com/host505/random/blob/main/plugin.video.cartoonsgr-1.0.26a.zip
All changes have been tested & working under kodi 18.9 & 19.3

### CODE REVIEW

**Comment by pitsi** [comment]
As requested, I am posting the issues of 1.0.26a here

There are 3 issues that are visible after a couple of seconds of usage and probably both are related to the new domain (tainies-online) itself.
ALL subcategories under there have the same content, there are almost no playable sources and there is only one page of results!

**Comment by host505** [comment]
I couldn't reproduce any of your issues (tested on k18 & 19 under win).
Maybe some lists have common items, but not exactly the same - after all the add-on lists what exists on the website. I checked the categories we use and they're on par add-on <==> site.
Next page also appears on lists and works.
About the links, yes, most of their older stuff are dead in the water, but newer stuff they add ahs links.

**Comment by pitsi** [comment]
Excluding screenshots, how can I prove that the issues I mention above do exist, when nothing relevant is mentioned in the log?

**Comment by host505** [comment]
It's not a matter of "prooving" it, I just want to see it replicated via log to understand what's wrong, as I can't replicate it.
You haven't even mentioned the platform you're running kodi on, what am I supposed to get out of such (no) info.
Eg if you're on linux, there may be some incompatibility with the python version bundled with your distribution. So, don't suppose "nothing relevant", most of the times the issue isn't written with big fat red letters.
Anyway, try resetting the Domains tab on settings, hit ok, clear cache and try again.
I since tried Android (19.3) and Coreelec (18.9) - all working fine. @kolekan have you tried it?

**Comment by kolekan** [comment]
> I couldn't reproduce any of your issues (tested on k18 & 19 under win). Maybe some lists have common items, but not exactly the same - after all the add-on lists what exists on the website. I checked the categories we use and they're on par add-on <==> site. Next page also appears on lists and works. About the links, yes, most of their older stuff are dead in the water, but newer stuff they add has links.
> 
> Clear add-on's cache, and if problem persists please share some logs.
I test it under Android - Kodi Matrix 19.3 and confirm your words host505.

**Comment by pitsi** [comment]
> It's not a matter of "prooving" it, I just want to see it replicated via log to understand what's wrong, as I can't replicate it. You haven't even mentioned the platform you're running kodi on, what am I supposed to get out of such (no) info. Eg if you're on linux, there may be some incompatibility with the python version bundled with your distribution. So, don't suppose "nothing relevant", most of the times the issue isn't written with big fat red letters. Anyway, try resetting the Domains tab on settings, hit ok, clear cache and try again. I since tried Android (19.3) and Coreelec (18.9) - all working fine. @kolekan have you tried it?

I mentioned my platforms on the original issue report on cartoonsgr for the domains. I am mentioning them again: kodi 18.9 on libreelec 9.2.6 x64 and kodi 19.3 on debian testing/unstable x64.
Libreelec 9.x (and any *elec 9.x) uses python2 (2.7.16) everywhere and its kodi is built with that version. There is no other python version anywhere in the distro.
Likewise, debian's kodi is built with python3 (3.9.x today) and it has removed python2 1+ year ago, so ALL its python related packages use python3 today.
Thus, there is no way the "wrong" python version was used anywhere. It was executed with the version that each distro supports.

After that clarification, let's continue our discussion on the relevant issue. I will clean the cache, reset the domains and post screenshots from the problem.

**Comment by host505** [comment]
You see, that's the problem with Linux. It uses the os's python, which sometimes is different from kodi's built-in python interpreter - which is what developers using and can test with (assuming they don't develop on linux).
Kodi 19's built-in python interpreter is 3.7, which has some differences on some of its built-in libs compared with py 3.9+ (namely urllib lib).
In short, it's impossible for me to debug linux installs - at least without user's logs.
It should work on libreelec though, as it uses kodi's python afaik.

**Pull request merged**
