### PR TITLE
Update settings.xml

### PR DESCRIPTION
**Pull request by Gazbhoy79**
New url for Rlsbb.unblockit.

### CODE REVIEW

**Comment by bugatsinho** [comment]
mate thank you but delete it cause the domains i change them on pastebin

**Comment by bugatsinho** [comment]
the domain is already there many months now
image

**Comment by Gazbhoy79** [comment]
Thank you for the reply. It unblockit. its doesn't work for me for months
but I think thats cos I'm from the UK so only way it will work for UK is
unblockit.cat. Ah well.

Your regards

Gaz

**Comment by bugatsinho** [comment]
i added unblockit.nz
restart kodi

**Comment by Gazbhoy79** [comment]
Dman sorry my bad I meant blockit.nz is working for UK but blockit.ict
didn't. If possible if you can add rlsb.blockit.nz on domains that would be
great. Much appreciated man.

**Comment by Gazbhoy79** [comment]
Sorry for the misunderstanding. Thank you very much mate. Will restart
kodi. you're a star.

**Pull request closed without merging**
