### PR TITLE
[CartoonsGR] Downloading: fix and py3/K19 compatibility

### PR DESCRIPTION
**Pull request by host505**

### CODE REVIEW

**Comment by host505** [comment]
Ready to install package with the changes of this pr is here:
https://github.com/host505/random/blob/main/plugin.video.cartoonsgr-1.0.28.1a.zip
Maybe @kolekan could test as well?

**Comment by kolekan** [comment]
I have tested already on Windows Kodi 19.3 and stream download works.

**Comment by host505** [comment]
@bugatsinho I see this change (among others) is included in some GrecoTM builds, but hasn't made it to this (I suppose) official repo?
That's not fare mate, I didn't make it for only GrecoTM builds users. I'm not even using one, so even me can't access it through a repo.

**Comment by bugatsinho** [comment]
> @bugatsinho I see this change (among others) is included in some GrecoTM builds, but hasn't made it to this (I suppose) official repo? That's not fare mate, I didn't make it for only GrecoTM builds users. I'm not even using one, so even me can't access it through a repo.

mate in greek builds possibly gkobu and others use your zip from here i didn't update the cartoon in my repo because i was off and didn't check your pull request. So plz next time contact me directly. so my apologies.

**Comment by bugatsinho** [comment]
cartoonsgr updated to 1.0.29

**Comment by host505** [comment]
I see... 
Btw tenies-online is broken, it seems they have fixed it on one of the builds, but won't contribute the fix here.
They're happy to take the work done here though.

**Comment by bugatsinho** [comment]
> I see... Btw tenies-online is broken, it seems they have fixed it on one of the builds, but won't contribute the fix here. They're happy to take the work done here though.

what i saw is that requests returns the home page html and not the page+ genres/kids

**Comment by bugatsinho** [comment]
TENIES-ONLINE FIXED on version 1.0.29.1

**Pull request merged**
