### PR TITLE
[sport365] Add multiple domains and setting to language

### PR DESCRIPTION
**Pull request by o1516876**

### CODE REVIEW

**Comment by bugatsinho** [comment]
nice addition.
thank you for your contribution!
can you explain me the reason of adding extra domains?

**Comment by o1516876** [comment]
> can you explain me the reason of adding extra domains?
Some ISP's in various countries block access to specific domains, so if we have multiple domains this block can be avoided and some domains could be faster depending on the country or ISP.

**Comment by bugatsinho** [comment]
> > can you explain me the reason of adding extra domains?
> 
> Some ISP's in various countries block access to specific domains, so if we have multiple domains this block can be avoided and some domains could be faster depending on the country or ISP.
> The main domain could be down and others up.

do you think it would be better to add the domain selection on settings as language there is alredy there?

**Comment by o1516876** [comment]
> do you think it would be better to add the domain selection on settings as language there is alredy there?

It depends, for an "advanced" user the domain setting could be the best option, but I doubt that a "newbie" will go to the settings if a domain doesn't work and it's easier to try with the following link until someone works.

I don't see any problem as it is now because sport365 is the only service with 4 different domains and advanced users can change the skin menu to access a specific domain without showing the main screen with 4 domains, but if you add more services it'll be more clear in the settings.

**Comment by bugatsinho** [comment]
https://github.com/bugatsinho/bugatsinho.github.io/commit/f51d3afdfdbb202d286b79bde6918f66c39c2c85

**Comment by bugatsinho** [comment]
> > do you think it would be better to add the domain selection on settings as language there is alredy there?
> 
> It depends, for an "advanced" user the domain setting could be the best option, but I doubt that a "newbie" will go to the settings if a domain doesn't work and it's easier to try with the following link until someone works.
> 
> I don't see any problem as it is now because sport365 is the only service with 4 different domains and advanced users can change the skin menu to access a specific domain without showing the main screen with 4 domains, but if you add more services it'll be more clear in the settings.
> 
> The best option should be a setting to choose between showing the 4 domains or 1 selectable domain.

https://github.com/bugatsinho/bugatsinho.github.io/commit/f51d3afdfdbb202d286b79bde6918f66c39c2c85

**Comment by AlbieNL** [comment]
The 2.5.2 version doesn't work for me (doesn't show streams ) , downgrade back to 2.5.1 then it all works again ??

**Comment by bugatsinho** [comment]
don't use shortcuts to open add-on root changed!

**Comment by AlbieNL** [comment]
Thanks for repley

If I work direct from addon it also doesn't  work 

Did full clean and restart after 2.5.2 install

When I open addon direct (true 'addons')  , I got 5 options , 2 off them lead to settings , 3 give a 3 digits ( like in ...) nothing else 

From there ^^^ again back to 2.5.1 and it works as before , also my hyperlink is 'super favorits' ans link used in skin 

Greats John from Netherlands

**Comment by AlbieNL** [comment]
And now 2.50 and 2.51 doensnt work anymore  either 

Yesterday evening these where good

**Comment by bugatsinho** [comment]
for sure is your setup or your ISP for me add-on works very well and for many other users!sorry but i cant help you...plz next time open an issue or post your kodi log file for futher investigation on your 
 issue!

**Comment by AlbieNL** [comment]
It works , as long i keep it on standard settings. If I change languese setting it stops working

Verstuurd vanaf mijn iPhone

**Pull request merged**
